-- https://wiki.hypr.land/Configuring/Basics/Autostart/
hl.on("hyprland.start", function ()
  hl.exec_cmd("awww-daemon")
  hl.exec_cmd("swaync")
  hl.exec_cmd("waybar -c ~/.config/waybar/config-ext.jsonc")
  hl.exec_cmd("steam")
  hl.exec_cmd("discord")
  hl.exec_cmd("ferdium")
  hl.exec_cmd("kdeconnect-indicator")
  hl.exec_cmd("wl-paste --watch cliphist store")
  hl.exec_cmd("wl-clip-persist --clipboard regular --reconnect-tries 0")
  hl.exec_cmd("blueman-applet")
  hl.exec_cmd("nm-applet")
  hl.exec_cmd("hyprctl setcursor Simp1e-Catppuccin-Latte 22")
  hl.exec_cmd("systemctl start --user hyprpolkitagent")
end)
